package:
  name: patchelf
  version: 0.8

source:
  fn: patchelf-0.8.tar.bz2
  url: http://nixos.org/releases/patchelf/patchelf-0.8/patchelf-0.8.tar.bz2
  sha1: d0645e9cee6f8e583ae927311c7ce88d29f416fc

build:
  number: 0

test:
  commands:
    - patchelf --help

about:
  home: http://nixos.org/patchelf.html
  license: GPL 3

# vim:set ts=8 sw=2 sts=2 tw=78 et: