package:
  name: git-lfs
  version: 1.1.2

build:
  number: 0

source:
  fn: git-lfs-linux-amd64-1.1.2.tar.gz # [linux64]
  url: https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz # [linux64]
  sha256: 30cda2c559eb6a870bb0768be22ad21bc015b3519f66811a42b2652c126cce7f # [linux64]
  fn: git-lfs-darwin-amd64-1.1.2.tar.gz # [osx]
  url: https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-darwin-amd64-1.1.2.tar.gz # [osx]
  sha256: 13ebc4523a4793522ca5217ad6080965321bd0cc213cfdd222ac1f740abd5fea # [osx]

requirements:
  run:
    - git

about:
  home: https://git-lfs.github.com/
  license: MIT
