package:
  name: astropy-helpers
  version: "1.1.1"

source:
  fn: astropy-helpers-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/a/astropy-helpers/astropy-helpers-1.1.1.tar.gz
  md5: 0a44c1c7038efaa065d18691fd768ff1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - astropy-helpers = astropy-helpers:main
    #
    # Would create an entry point called astropy-helpers that calls astropy-helpers.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - sphinx
    - pytest
    - python
    - setuptools

  run:
    - sphinx
    - pytest
    - python

test:
  # Python imports
  imports:
    - astropy_helpers
    - astropy_helpers.commands
    - astropy_helpers.compat
    - astropy_helpers.sphinx
    - astropy_helpers.sphinx.ext
    - astropy_helpers.sphinx.ext.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://astropy.org
  license: BSD License
  summary: 'Utilities for building and installing Astropy, Astropy affiliated packages, and their respective documentation.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

build:
  number: 0
  string: "0"
  number: 0
