package:
  name: lsst-glib
  version: 2.43.0

source:
  fn: glib-2.43.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/glib/2.43/glib-2.43.0.tar.xz
  sha256: b01efba5a9301a4ae32f5d5623bcda31917839d4f1bfe879775b2df34c8cfdd7

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - gcc
    # XXX https://github.com/mjuric/conda-lsst/issues/41
    #- libffi >=3.0.0
    - lsst-libffi
    - zlib
  run:
    - lsst-libffi >=3.0.0
    - zlib

about:
  license: LGPL
  home: https://developer.gnome.org/glib/
  summary: "GLib provides the core application building blocks for libraries and applications written in C. "
